const constants = {
    BUY_PRODUCT: "BUY_PRODUCT",
    ADD_PRODUCT: "ADD_PRODUCT",
    FETCH_PRODUCT_NAMES: "FETCH_PRODUCT_NAMES",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS"
};

export default constants;