const constants = {
    NOTIFICATION_ERROR: "NOTIFICATION_ERROR",
    NOTIFICATION_SUCCESS: "NOTIFICATION_SUCCESS",

    ATTEMPT_LOGIN: "ATTEMPT_LOGIN",
    LOGIN: "LOGIN",
    FAIL_LOGIN: "FAIL_LOGIN",
    LOGOUT: "LOGOUT",

    UPDATE_CART: "UPDATE_CART",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CLEAR_CART: "CLEAR_CART",

    SAVE_PROGRESS: "SAVE_PROGRESS",
    RESET_PROGRESS: "RESET_PROGRESS",
    SAVE_PHASE: "SAVE_PHASE",
    CHECKOUT: "CHECKOUT",

    DISPLAY_NOTIFICATION: "DISPLAY_NOTIFICATION",
    HIDE_NOTIFICATION: "HIDE_NOTIFICATION",

    UPDATE_CATEGORIES: "UPDATE_CATEGORIES"
};

export default constants;